apiVersion: apps/v1
kind: Deployment
metadata:
  name: one-to-one-jpa
  labels:
    app: one-to-one-jpa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: one-to-one-jpa
  template:
    metadata:
      labels:
        app: one-to-one-jpa
    spec:
      containers:
      - name: one-to-one-jpa
        image: surmis/onetoonejpa:latest
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: demo-service
spec:
  selector:
    app: one-to-one-jpa
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30008
  type: LoadBalancer
  